[chest-xray-multiple]
Shell="~/public_html/myenv/bin/python3"

[chest-xray-tuberculosis]
Shell="~/public_html/myenv/bin/python3"

[clinical-modernbert]
Shell="~/public_html/myenv/bin/python3"

[text-similarity]
Shell="~/public_html/myenv/bin/python3"

[voice-to-text]
Shell="~/public_html/myenv/bin/python3"


