[text-similarity]
Shell="~/public_html/myenv/bin/python3"
Port="5001"

[text-text-similarity]
Shell="~/public_html/myenv/bin/python3"
Port="5001"

[voice-to-text]
Shell="~/public_html/myenv/bin/python3"
Port="5002"

[chest-xray-multiple]
Shell="~/public_html/myenv/bin/python3"
Port="5003"

[chest-xray-tuberculosis]
Shell="~/public_html/myenv/bin/python3"
Port="5004"

[clinical-modernbert]
Shell="~/public_html/myenv/bin/python3"
Port="5005"

[er-mortality]
Shell="~/public_html/myenv/bin/python3"
Port="5006"

[text-correction]
Shell="~/public_html/myenv/bin/python3"
Port="5007"

[image-text-similarity]
Shell="~/public_html/myenv/bin/python3"
Port="5008"




