[text-similarity]
Shell="~/public_html/myenv/bin/python3"
Name="FremyCompany/BioLORD-2023-C"
URL="https://huggingface.co/FremyCompany/BioLORD-2023-C"
Port="5001"

[text-text-similarity]
Shell="~/public_html/myenv/bin/python3"
Name="FremyCompany/BioLORD-2023-C"
URL="https://huggingface.co/FremyCompany/BioLORD-2023-C"
Port="5001"

[voice-to-text]
Shell="~/public_html/myenv/bin/python3"
Name="nvidia/parakeet-tdt-0.6b-v3"
URL="https://huggingface.co/nvidia/parakeet-tdt-0.6b-v3"
Port="5002"

[chest-xray-multiple]
Shell="~/public_html/myenv/bin/python3"
Name="codewithdark/vit-chest-xray"
URL="https://huggingface.co/codewithdark/vit-chest-xray"
Port="5003"

[chest-xray-tuberculosis]
Shell="~/public_html/myenv/bin/python3"
Name="sukhmani1303/tuberculosis-vit-model"
URL="https://huggingface.co/sukhmani1303/tuberculosis-vit-model"
Port="5004"

[clinical-modernbert]
Shell="~/public_html/myenv/bin/python3"
Name="Simonlee711/Clinical_ModernBERT"
URL="https://huggingface.co/Simonlee711/Clinical_ModernBERT"
Port="5005"

[er-mortality]
Shell="~/public_html/myenv/bin/python3"
Name="kripa35/ER-Mortality-Prediction"
URL="https://github.com/kripa35/ER-Mortality-Prediction"
Port="5006"

[text-correction]
Shell="~/public_html/myenv/bin/python3"
Name=""
URL=""
Port="5007"

[image-text-similarity]
Shell="~/public_html/myenv/bin/python3"
Name="google/medsiglip-448"
URL="https://huggingface.co/google/medsiglip-448"
Port="5008"

[voice-to-text-clinical]
Shell="~/public_html/myenv/bin/python3"
Name="google/medasr"
URL="https://huggingface.co/google/medasr"
Port="5009"




