' Gambas module file

Private $appSetting As String = "/etc/analyzeml/appsettings.conf"

Public Function ShowModelsSettingFromFIle(strSetting As String) As String

  Dim ConfFile As Settings
  Dim strVal As String
  Dim xx As String

  If Exist($appSetting) Then
    ConfFile = New Settings($appSetting)
    strVal = ConfFile[strSetting, Null]
    If strVal Then
      xx = Trim(strVal)
    Else
      xx = ""
    Endif
  Else
    xx = ""
  Endif
  Return xx

End
