[ipython]
Shell="/home/safiur/public_html/myenv/bin/ipython3"

[Clinical-ModernBERT]
Name="ModernBERT"
URL="http://localhost/cgi-bin/web-api"

[word2vec]
ModelPath="/home/safiur/Project/models/wordvec/w2v_OA_CR_100d.bin"
HubURL="https://huggingface.co/garyw/clinical-embeddings-100d-w2v-cr/tree/main"

[model2vec]
ModelPath="/home/safiur/Project/models/bio_clinicalbert_m2v"
HubURL="https://huggingface.co/emilyalsentzer/Bio_ClinicalBERT/tree/main"
