[Clinical-ModernBERT]
Name="ModernBERT"
URL="http://localhost/cgi-bin/web-api"

[WordVectorizer]
ModelPath="/home/safiur/Project/models/wordvec/w2v_OA_CR_100d.bin"
HubURL="https://huggingface.co/garyw/clinical-embeddings-100d-w2v-cr/tree/main"
